### ISSUE TITLE
nixt(...).touch is not a function

### ISSUE THREAD

**Issue by nkbt** [vesln/nixt#16]
I've just followed README, created `nixt.js` file with

```js
var nixt = require('nixt');

nixt()
  .touch('/tmp/test')
  .run('ls /tmp/')
  .stdout(/test/)
  .end();
```

Run it with `node nixt` and got error:

```sh
22:40 $ node nixt
/Users/nkbt/github/p-s/nixt.js:4
  .touch('/tmp/test')
   ^

TypeError: nixt(...).touch is not a function
    at Object.<anonymous> (/Users/nkbt/github/p-s/nixt.js:4:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

I did some debugging and it does not look like docs match the code =(, nixt instance does not have any of those methods.

On a side note I have a general question if the project is alive and maintained.

Cheers, 
Nik

**Comment by eush77** [comment]
Yeah, it seems `.touch` was replaced with `.writeFile` early on and never really implemented.

You can use `.exec('touch file')` or `.writeFile('file', '')` instead (note that the latter doesn't update `atime` and overwrites the file if it exists).

I've just updated the docs.
